### ISSUE TITLE
Documentation optimisation

### ISSUE THREAD

**Issue by ichesnokov** [Hydroque/LuaConsole#5]
Hi, thank you for installation instructions for LuaRocks at https://github.com/Hydroque/LuaConsole/wiki/LuaRocks-Support-Windows-MinGW.

I just want to suggest a small optimisation: instead of doing `install /F /MW /L` and then deleting "all lua51 executables, MSVCRT stuff, manifest, and lua51.dll, and everything in \include" as described at step (5), isn't it easier to skip the `/L` switch during installation?

lua51 executables/dlls won't be installed in this case at all.

**Comment by Hydroque** [comment]
Well the problem I had with that is when I decided it was time to install it, a lua executable MUST of been present, as it would use it for compilation reasons. So, the guide sets up LuaRocks manually for use with it. Else use the default one supplied. Lua is a dependency for it.

HOWEVER, it is possible to set it up using prefix and the like, which was suggested to me by the maintainer of LuaRocks whilst I was complaining about LuaRocks forcing me to use tuples instead of `{...} or arg`

So I will improve it over time, yes, but I haven't had the chance to explicitly do that as testing is required.

**Comment by Hydroque** [comment]
I added clarification to it. I might want to reformat the whole wiki.

**Comment by Hydroque** [comment]
Hey, you might want to rebuild. I just added some major bug fixes that came with the implementation of LuaJIT that breaks a lot of the code.
